version: '3'

tasks:
  build:
    desc: "build terraform provider"
    cmd: go build -o terraform-provider-monad .

  example-apply:
    desc: "Run example terraform file in examples directory"
    dir: examples
    deps:
      - build
    cmd: TF_LOG=DEBUG  terraform apply -auto-approve

  example-destroy:
    desc: "Run destroy on example terraform file in examples directory"
    dir: examples
    deps:
      - build
    cmd: TF_LOG=DEBUG  terraform destroy -auto-approve

  example-apply-and-destroy:
    desc: "Run apply and destroy on example terraform file in examples directory"
    dir: examples
    deps:
      - build
    cmds:
      - task: example-apply
      - task: example-destroy