#!/usr/bin/env bash
# Cross-check the hand-written registry docs against the provider schema.
#
#   ./scripts/check-doc-attributes.sh
#
# docs/ is generated by tfplugindocs from templates/, but the Argument Reference
# and Attribute Reference sections in those templates are written by hand (in
# the style of the hashicorp/aws provider) rather than emitted from the schema.
# That buys prose, examples and nested-block sections the generator cannot
# produce — and loses the guarantee that every attribute is documented. This
# script restores the guarantee: every attribute or block name declared in a
# resource's Go schema must appear, backticked, in that resource's template.
#
# Exit 1 on any undocumented attribute, so this can gate CI.
set -euo pipefail

cd "$(dirname "$0")/.."

# schema source file -> templates that document it (space-separated after the
# colon). resource_connector.go is shared by monad_input and monad_output.
# A plain list rather than an associative array: macOS ships bash 3.2.
sources="
internal/provider/provider.go:templates/index.md.tmpl
internal/provider/resource_connector.go:templates/resources/input.md.tmpl templates/resources/output.md.tmpl
internal/provider/resource_enrichment.go:templates/resources/enrichment.md.tmpl
internal/provider/resource_transform.go:templates/resources/transform.md.tmpl
internal/provider/resource_pipeline.go:templates/resources/pipeline.md.tmpl
internal/provider/resource_secret.go:templates/resources/secret.md.tmpl
internal/provider/resource_alert_rule.go:templates/resources/alert_rule.md.tmpl
"

total=0; missing=0
while IFS= read -r line; do
  [ -n "$line" ] || continue
  src="${line%%:*}"
  tmpls="${line#*:}"
  [ -f "$src" ] || { echo "no such schema file: $src" >&2; exit 2; }
  # Attribute and block declarations look like:   "name": schema.StringAttribute{
  # and the framework-timeouts block like:        "timeouts": timeouts.Block(
  attrs=$(grep -oE '^[[:space:]]*"[a-z_]+":[[:space:]]*(schema|timeouts)\.' "$src" \
    | sed -E 's/^[[:space:]]*"([a-z_]+)".*/\1/' | sort -u)
  for tmpl in $tmpls; do
    [ -f "$tmpl" ] || { echo "no such template: $tmpl" >&2; exit 2; }
    while IFS= read -r attr; do
      [ -n "$attr" ] || continue
      total=$((total + 1))
      if ! grep -qF "\`$attr\`" "$tmpl"; then
        echo "MISSING    $attr — declared in $src, not documented in $tmpl"
        missing=$((missing + 1))
      fi
    done <<< "$attrs"
  done
done <<< "$sources"

echo
if [ "$missing" -eq 0 ]; then
  echo "OK: all $total schema attributes are documented in templates/"
  exit 0
fi
echo "FAIL: $missing of $total schema attributes are undocumented"
echo "Add each one to the resource's template under Argument Reference or Attribute Reference."
exit 1
